spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

security:
  jwt:
    secret: ${JWT_SECRET}
    access-token-ttl-minutes: ${JWT_ACCESS_TOKEN_TTL_MINUTES}
    refresh-token-ttl-days: ${JWT_REFRESH_TOKEN_TTL_DAYS}

  pii:
    key: ${ENCRYPTION_KEY}
    hash-salt: ${HASH_SALT}

  login:
    max-attempts: 5
    window-seconds: 600
    block-seconds: 1800